// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://helaleedscdpdxwlgrnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlbGFsZWVkc2NkcGR4d2xncm52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTY1NDksImV4cCI6MjA1ODY3MjU0OX0.UvbiuIlDe4O8KL6x85GhnGpOMEeb3Jg2f3ezTsXUlPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);